version: '3.8'

services:
  php:
    build: .
    container_name: php81
    volumes:
      - ./:/var/www/sugarcv.co.uk
    ports:
      - "9000:9000"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge