version: '3.8'

services:
  php:
    build: .
    container_name: php81
    volumes:
      - ./:/var/www/sugarcv.co.uk
    networks:
      - host-net

networks:
  host-net:
    external: true
    name: host